name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.nim == 'devel' }}
    strategy:
      fail-fast: false
      matrix:
        nim: ['1.6.x', '2.0.x', '2.2.x', 'devel']
    steps:
      - uses: actions/checkout@v6
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: nimble test -y
